language: node_js
sudo: false
node_js:
- '6'
cache:
  yarn: true
  directories:
  - bower_components
branches:
  except:
  - "/^g3_.*$/"
env:
  matrix:
  - JOB=ci-checks
  - JOB=unit BROWSER_PROVIDER=saucelabs
  # - JOB=docs-e2e BROWSER_PROVIDER=saucelabs
  # - JOB=e2e TEST_TARGET=jqlite BROWSER_PROVIDER=saucelabs
  # - JOB=e2e TEST_TARGET=jquery BROWSER_PROVIDER=saucelabs
  global:
  - CXX=g++-4.8
  - SAUCE_USERNAME=angular-ci
  - SAUCE_ACCESS_KEY=9b988f434ff8-fbca-8aa4-4ae3-35442987
  - LOGS_DIR=/tmp/angular-build/logs
  - BROWSER_PROVIDER_READY_FILE=/tmp/browsersprovider-tunnel-ready
  - secure: oTBjhnOKhs0qDSKTf7fE4f6DYiNDPycvB7qfSF5QRIbJK/LK/J4UtFwetXuXj79HhUZG9qnoT+5e7lPaiaMlpsIKn9ann7ffqFWN1E8TMtpJF+AGigx3djYElwfgf5nEnFUFhwjFzvbfpZNnxVGgX5YbIZpe/WUbHkP4ffU0Wks=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_script:
- du -sh ./node_modules ./bower_components/ || true
- "./scripts/travis/before_build.sh"
script:
 - "./scripts/travis/build.sh"
after_script:
- "./scripts/travis/tear_down_browser_provider.sh"
- "./scripts/travis/print_logs.sh"
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/d2120f3f2bb39a4531b2
    - http://104.197.9.155:8484/hubot/travis/activity
    on_success: always
    on_failure: always
    on_start: always
jobs:
  include:
    - stage: deploy
      env:
        - JOB=deploy
      before_script: skip
      script:
       - "./scripts/travis/build.sh"
       - echo 'SAUCE_ACCESS_KEY'
       - echo $SAUCE_ACCESS_KEY
       - echo 'DIST_TAG?'
       - echo $DIST_TAG
       - echo 'TRAVIS_TAG?'
       - echo $TRAVIS_TAG
      # Work around the 10min Travis timeout. The firebase / gcs code deploy does not report
      # back to the process
      before_deploy: |
        function keep_alive() {
          while true; do
            echo -en "\a"
            sleep 5
          done
        }
        keep_alive &
      deploy:
        - provider: firebase
          skip_cleanup: true
          token:
            secure: $FIREBASE_TOKEN
          on:
            repo: angular/angular.js
            condition: $TRAVIS_TAG = '' && $DIST_TAG = next
            all_branches: true
        - provider: gcs
          access_key_id: GOOGLDB7W2J3LFHICF3R
          secret_access_key:
            secure: tHIFdSq55qkyZf9zT/3+VkhUrTvOTMuswxXU3KyWaBrSieZqG0UnUDyNm+n3lSfX95zEl/+rJAWbfvhVSxZi13ndOtvRF+MdI1cvow2JynP0aDSiPffEvVrZOmihD6mt2SlMfhskr5FTduQ69kZG6DfLcve1PPDaIwnbOv3phb8=
          bucket: code-angularjs-org-338b8.appspot.com
          local-dir: upload
          skip_cleanup: true
          detect_encoding: true # detects gzip compression
          on:
            repo: angular/angular.js
            all_branches: true
            condition: $TRAVIS_TAG != '' || ($TRAVIS_PULL_REQUEST = false && $TRAVIS_BRANCH = master)

